version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: app
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always

  phpmyadmin:
    container_name: phpadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8082:80'
    environment:
      PMA_HOST: mysql


  springbootintegration:
    build: .
    volumes:
    - .:/app
    - ~/.m2:/root/.m2
    working_dir: /app
    ports:
    - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
    - mysql
